### ISSUE TITLE
Rename branches and give meaningful tags

### ISSUE THREAD

**Issue by melonux** [MerlinLayer2/merlin-cdk-validium-contracts#3]
Go through Github webpages to
1. Rename `main` branch to `old_fork5` 
2. Rename `upgrade_validium` branch to `main` 
3. Change default branch to `main`

old_fork5 HEAD => tag: fork5
`git tag fork5 083234f`

upgrade_validium HEAD => tag: fork8
`git tag fork8 5f233ee`

push tag to origin
`git push origin fork5`
`git push origin fork8`

**Comment by mer-coder** [comment]
Done
